apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-volume
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  - name: html-updater
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - while true; do date >> /html/index.html; sleep 10; done
    resources:
      requests:
        memory: "32Mi"
        cpu: "25m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    volumeMounts:
      - name: html
        mountPath: /html
  volumes:
  - name: html
    hostPath:
      # This path depends on your OS (see README for details)
      path: /private/tmp/html

# kubectl apply -f nginx-alpine-emptyDir.pod.yml
# kubectl port-forward nginx-alpine-volume 8080:80
