apiVersion: v1
kind: Service
metadata:
  name: pluralsight-ftw
spec:
  publishNotReadyAddresses: true
  selector:
    app: initializer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer