# Removido o StorageClass customizado, vamos usar o 'standard' do Minikube
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pvc-ro
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-ro
  namespace: default
subjects:
- kind: ServiceAccount
  name: "reader"
  namespace: default
roleRef:
  kind: Role 
  name: pvc-ro 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-finale-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard # <--- MUDANÇA AQUI: Use o padrão do Minikube
  resources:
    requests:
      storage: 1Gi # 1GB é mais que suficiente para esse lab
---
apiVersion: v1
kind: Service
metadata:
  name: finale-svc
spec:
  selector:
    app: finale-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: finale-1
  labels:
    app: finale-1
spec:
  serviceAccountName: reader
  volumes:
  - name: vol-data
    persistentVolumeClaim:
      claimName: pvc-finale-1
  securityContext:
    fsGroup: 0
    runAsUser: 0
  initContainers:
  - name: init-pv 
    image: nigelpoulton/k8s-api-proxy:1.0
    command: ["sh", "-c"]
    args: ["until kubectl get pvc pvc-finale-1; do echo waiting for PVC; sleep 1; done; echo PVC found!"]
  - name: init-sync
    image: k8s.gcr.io/git-sync:v3.1.5
    volumeMounts:
    - name: vol-data
      mountPath: "/tmp/git"
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/nigelpoulton/ps-sidecar.git
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_ROOT
      value: "/tmp/git"
    - name: GIT_SYNC_DEST
      value: "html"
    - name: GIT_SYNC_ONE_TIME
      value: "true"  
  - name: init-svc
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup finale-svc; do echo waiting for service; sleep 2; done; echo Service found!']  
  containers:
  - name: app
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx"
        name: vol-data
  - name: sidecar-sync
    image: k8s.gcr.io/git-sync:v3.1.5
    volumeMounts:
    - name: vol-data
      mountPath: "/tmp"
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/nigelpoulton/ps-sidecar.git
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_DEST
      value: "html"