apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: montiramento
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucassantosf/devops.git
    targetRevision: HEAD
    path: argocd/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoramento
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true