apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webcolor
  namespace: argocd
spec:
  template:
    metadata:
      name: 'webcolor-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lucassantosf/k8s-web-color-page.git
        targetRevision: HEAD
        path: k8s
      destination:
        server: '{{server}}'
        namespace: webcolor
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  generators:
    - clusters: {}