{
 "title": "Falco",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Identified Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"falco\"} [$__range]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Event Severity Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"falco\"} | json priority=\"[\\\"priority\\\"]\" [$__range])",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Events by container",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (container_name) (\n  count_over_time({job=\"falco\"} \n    | regexp `container.name=(?P<container_name>[^ ]+)` \n    [$__range])\n)\n",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Triggered Rules Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (rule) (count_over_time({job=\"falco\"} | json rule=\"[\\\"rule\\\"]\" | drop __error__, __error_details__ | rule!=\"\" [$__auto]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Events Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"falco\"} [$__interval]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Top Triggered Rules",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (rule) (\n  count_over_time({job=\"falco\"} \n    | json rule=\"rule\" \n    | rule!=\"\" \n    [$__range])\n))\n",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"falco\"} | json"
    }
   ]
  }
 ]
}